version: "3.9"

services:
    app1:
        build:
            context: .
            dockerfile: Dockerfile-app
        environment:
          - DATABASE_URL=sqlite:////app/database/sql_app.db
        ports:
            - "8081:8000"

    app2:
        build:
            context: . 
            dockerfile: Dockerfile-app
        environment:
          - DATABASE_URL=sqlite:////app/database/sql_app.db
            - "8082:8000"

    app3:
        build:
            context: .
            dockerfile: Dockerfile-app
        environment:
          - DATABASE_URL=sqlite:////app/database/sql_app.db
        ports:
            - "8083:8000"

    loadbalancer:
        build:
            context: .
            dockerfile: loadbalancer/Dockerfile-loadbalancer
        ports:
            - "8080:8000"
        depends_on:
            - app1
            - app2
            - app3
    
    database:
        build:
            context: .
            dockerfile: database/Dockerfile-database